version: '3.3'
services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: 'True'
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  celery:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: celery
    volumes:
      - ./server:/server
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - server
      - redis
    command: celery --app=config worker -l INFO

  celery-beat:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: celery-beat
    volumes:
      - ./server:/server
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - server
      - redis
      - celery
    command: celery --app=config beat -l INFO

  redis:
    image: redis:7-alpine3.17
    container_name: redis