# Generated by Django 3.2.2 on 2023-07-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
    ]
