# Generated by Django 3.2.2 on 2023-07-23 09:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pockets', '0003_auto_20230710_2235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together={('user', 'name')},
        ),
    ]
