# Generated by Django 3.2.2 on 2023-08-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0004_alter_transactioncategory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('percents', 'Проценты')], max_length=8, null=True, verbose_name='Тип категории'),
        ),
    ]
