# Generated by Django 3.2.2 on 2023-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='expire_date',
            field=models.DateField(null=True, verbose_name='Дата окончания срока'),
        ),
    ]
