# Generated by Django 3.2.2 on 2023-07-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='expire_date',
        ),
    ]
