# Generated by Django 3.2.2 on 2023-07-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goal_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('в процессе', 'процессе'), ('завершена', 'завершена')], default='в процессе', max_length=10, verbose_name='Тип категории'),
        ),
    ]
