# Generated by Django 3.2.2 on 2023-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
    ]
