# Generated by Django 3.2.2 on 2023-08-07 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_target_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
