# Generated by Django 3.2.2 on 2023-07-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='status',
            new_name='is_completed',
        ),
    ]
